# Copyright 2023, OpenHW Group
# SPDX-License-Identifier:Apache-2.0 WITH SHL-2.1

name: aws

on:
  push:
    branches:
      - 'aws_ci_migration'

jobs:
  #aws:
  #  name: AWS Pipeline (private)
  #  if: ${{ (github.actor == 'MikeOpenHWGroup' || github.actor == 'suppamax') && github.event.label.name != 'Component:Doc' }}
  #  runs-on: ubuntu-latest
  #  # These permissions are needed to interact with GitHub's OIDC Token endpoint.
  #  permissions:
  #    id-token: write
  #    contents: read
  #  steps:
  #    - name: Configure AWS Credentials
  #      uses: aws-actions/configure-aws-credentials@v1
  #      with:
  #        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  #        aws-region: eu-west-1
  #    - name: Run AWS Pipeline
  #      uses: openhwgroup/aws-codebuild-run-build@master
  #      with:
  #        project-name: cv32e40p
  #        hide-log: true
  skip_aws:
    name: no ci_check required for documentation
    #if: ${{ (github.actor == 'MikeOpenHWGroup' || github.actor == 'suppamax') && github.event.label.name == 'Component:Doc' }}
    if: ${{ github.actor == 'MikeOpenHWGroup' || github.actor == 'MikeCovrado' }}
    runs-on: ubuntu-latest
    steps:
      - name: info
        run: echo "Documentation only, skipping CI_CHECK on AWS"
